### ISSUE TITLE
[BUG] Role prisma schema may conflict with client specifications

### ISSUE THREAD

**Issue by FegelSamuel** [UTDallasEPICS/ATC-Patient-Data#19]
**Describe the bug**
There are two different user creation pages (student and employee). Each of them accept different sets of data, but we only have one user schema that doesn't account for differences in data sets. 

**Why is it important?**
The role permission system is the main priority of focus and it's not properly implemented upon further inspection. 

**Expected behavior**
We don't know the expected behavior for sure, we have to ask the client again. 

**Additional context**
Client must be asked about what functionality they want.
enum Datatype { } located in the prisma schema doesn't match the values specified on line 122-125 pages/behaviors/add.tsx

**Comment by pariahGH** [comment]
The User table contains properties common to all users. Employees vs Patients is described with the EmployeeProfile and PatientProfile tables. You can create the profile for a User at the same time that you are creating the user as seen here https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries#create-a-related-record
