### ISSUE TITLE
SP24 - Fix Search

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/ATC-Patient-Data#2]
- search function is used whenever we are listing an item
- can specify which model we are searching, which parameters to get, and what search parameters to use
- use prisma to run the query and get the total number of results - we are limiting to 20 results per page. the id of the last result in a page is the 'cursor' - the next 'page' is all ids bigger than this one for the same search parameters.
- frontend support - component that takes search input and uses hardocded filters (right now only user controllable search input is text - we hardcode the search filter and selected data for now)

**Comment by FegelSamuel** [comment]
The Search function is broken right now, fix it ASAP because it helps testing other things like the `profile.tsx` file you will see in the `pages` directory
