### ISSUE TITLE
F23 - each 'get' function needs to get a single item of that type, by ID

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/ATC-Patient-Data#3]
- getting multiple of anything is handled by the search route

**Comment by FegelSamuel** [comment]
Where are the files that contain the get functions in question located?

**Comment by pariahGH** [comment]
For example in `program.ts`, we have two functions for getting - `getPrograms` and `getProgramById`. `getPrograms` is used by the switch statement at the top. This should be reduced to just a single `getProgram` function that only gets a single program. This pattern should then be applied to all the other API route files.

**Comment by FegelSamuel** [comment]
I think Ryosuke completed this.
