### ISSUE TITLE
[CLIENT LIAISON] Distinction between Admin and BCBA

### ISSUE THREAD

**Issue by FegelSamuel** [UTDallasEPICS/ATC-Patient-Data#52]
BCBA and Admins are probably the same, but make sure to clear it up with Marilyn Reid before deleting the `ADMIN` xor `BCBA` in favor of the other. The role enums are in `~/prisma/schemas.prisma`

**Comment by rach-mathew** [comment]
BCBA and Admin are the same. BCBA can de disregarded
