### ISSUE TITLE
F23 - Convert js components to tsx

### ISSUE THREAD

**Issue by pariahGH** [UTDallasEPICS/ATC-Patient-Data#6]

**Comment by magbuv** [comment]
what resources can we use to solve this issue?

**Comment by pariahGH** [comment]
https://medium.com/@tgknapp11/next-js-converting-js-components-to-tsx-components-5e35a2fc1e70

This shouldn't involve too much heavy lifting, as we really just need to add types and update the extension

**Comment by magbuv** [comment]
Which files in particular are we converting to Typescript?

**Comment by pariahGH** [comment]
All of them

You may have to create types - put these in a central `types.ts` folder, this way we can ensure consistency across the codebase. In the future we will try to make some of the type definitions use the prisma definitions
