### ISSUE TITLE
Student Search Page

### ISSUE THREAD

**Issue by rigrergl** [UTDallasEPICS/ATC-Patient-Data#72]

**Comment by rigrergl** [comment]
- GET API for student data
- Vue component/page for student search

**Comment by emoryjgrubbs** [comment]
The functionality is mostly complete; it just needs to be updated to give the user's role and archive search type variables to the Search APIs.
UI needs to be created in tailwind.

**Comment by TusharW4ni** [comment]
The students page now shows a table of students with columns name and assigned employee. Name has student's first and last name together, and assigned employee shows that employee's first name. The search can search through student's first and last names. We can talk about also searching through assigned employees. 

The page also has a toggle to search in archived students or not.

The page also has a component to add students. However, that form does not have validation. That needs to be worked on next. I will put this task on the done board, make a new task, and put the link here too for reference.
