### ISSUE TITLE
Consistent Naming

### ISSUE THREAD

**Issue by rigrergl** [UTDallasEPICS/ATC-Patient-Data#9]
**Feature Description**
Make sure that all entities have consistent naming.

**Requirements**
Example: "Behavior" the DB entity and "behaviour" the endpoint should have the same name.

**Additional context**
This will help us avoid confusion and move faster in the future.

**Comment by FegelSamuel** [comment]
# End of Semester
* At the end of the semester, when all PRs are through, someone needs to set all patient names to students.
